### PR TITLE
Use lower case variable names

### PR DESCRIPTION
**Pull request by nikolai-b**
Do not rename the variables to have upper case
Use msoa1 and 2 instead of Work and Residence

### CODE REVIEW

**Comment by Robinlovelace** [comment]
Looks good - ping me when this is in pct-bigdata and I'll do a test build for Cambridgeshire.

**Comment by nikolai-b** [comment]
I'm testing for cam now!

**Comment by nikolai-b** [comment]
PRs in load and shiny to follow ASAP

**Comment by Robinlovelace** [comment]
Safe - please can you send me the model output html file it generates or just push to NPT0 the latest version? Anna made some changes to `model_output.Rmd` and wants to see how they look so feel free to cc her in when the new data (+ model output html) is up there. Great work!

**Pull request merged**
